### ISSUE TITLE
DB Shutdown Exception

### ISSUE THREAD

**Issue by musch711** [BeerTrader/BeerTraderService#4]

**Comment by musch711** [comment]
Shutting down the Tomcat server yields the following:
INFO: Stopping service Catalina
Feb 02, 2015 9:44:34 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/beertrader] appears to have started a thread named [Neo4j UDC Timer] but has failed to stop it. This is very likely to create a memory leak.
Feb 02, 2015 9:44:34 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/beertrader] appears to have started a thread named [GC-Monitor] but has failed to stop it. This is very likely to create a memory leak.
Feb 02, 2015 9:44:34 PM org.apache.coyote.http11.Http11Protocol destroy
INFO: Stopping Coyote HTTP/1.1 on http-8080
Exception in thread "Thread-10" java.lang.NoClassDefFoundError: org/neo4j/kernel/AvailabilityGuard$3
	at org.neo4j.kernel.AvailabilityGuard.shutdown(AvailabilityGuard.java:141)
	at org.neo4j.kernel.InternalAbstractGraphDatabase.shutdown(InternalAbstractGraphDatabase.java:821)
	at com.db.DataManager$1.run(DataManager.java:66)
Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.AvailabilityGuard$3
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1680)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)
	... 3 more
